language: go

go:
  - 1.11.x

jobs:
  include:
    - stage: "Install Dependencies"
      name: "Install golang/dep"
      script: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - name: "Insall Go Dependencies"
      script: make dep
    - stage: "Build"
      script: make
