required = ["github.com/fsouza/go-dockerclient", "github.com/smartystreets/goconvey/convey", "github.com/sirupsen/logrus", "github.com/docker/docker"]

[prune]
  go-tests = true
  unused-packages = true
